# Combining all the cleaned datasets

In [1]:
import pandas as pd
import numpy as np

Load all the cleaned data

In [2]:
healthDF = pd.read_csv('../Clean Data/healthcareData.csv')
socioEcDF = pd.read_csv('../Clean Data/socioeconomicData.csv')
educationDF = pd.read_csv('../Clean Data/educationData.csv')

Merge data together

In [3]:
combinedHealthcareAndSocioEconomicDF = pd.merge(healthDF,socioEcDF,on='tractID')

In [4]:
finalDF = pd.merge(combinedHealthcareAndSocioEconomicDF,educationDF,on='tractID')

Validate final dataframe and do a little bit of cleaning

In [5]:
finalDF.head()

,stateInitials,stateName,countyName,countyID,tractID,population,noHealthInsurance%,arthritis%,bingeDrinking%,highBP%,...,"%SomeCollege,NoDegree",%AssociatesDegree,%BachelorsDegree,%GraduateOrProfessionalDegree,%PercentHighSchoolGraduateOrHigher,%PercentBachelorsDegreeOrHigher,%PovertyLessThanHighSchoolGraduate,%PovertyHighSchoolGraduate,%PovertySomeCollegeOrAssociatesDegree,%PovertyBachelorsDegreeOrHigher
0,AZ,Arizona,Maricopa,4013,4013422643,5789,11.9,17.0,19.9,23.7,...,28.8,12.5,23.8,9.8,95.3,33.5,14.8,10.0,5.7,2.0
1,CA,California,Sacramento,6067,6067007402,6180,15.4,24.6,19.6,30.5,...,24.7,7.8,9.9,3.2,82.9,13.1,45.0,23.5,13.3,6.9
2,AL,Alabama,Madison,1089,1089000201,760,25.4,36.0,10.5,53.7,...,27.3,6.0,7.8,2.5,74.3,10.3,45.8,20.4,26.4,22.6
3,AL,Alabama,Montgomery,1101,1101002202,1185,25.2,36.1,10.9,54.6,...,12.0,3.7,3.4,0.9,68.1,4.3,35.5,26.6,19.2,0.0
4,AL,Alabama,Butler,1013,1013952800,1394,14.3,36.0,13.4,43.0,...,17.3,10.3,20.3,13.8,91.2,34.1,19.8,21.7,10.2,10.5

In [6]:
finalDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71580 entries, 0 to 71579
Data columns (total 84 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   stateInitials                          71580 non-null  object
 1   stateName                              71580 non-null  object
 2   countyName                             71580 non-null  object
 3   countyID                               71580 non-null  int64
 4   tractID                                71580 non-null  int64
 5   population                             71580 non-null  int64
 6   noHealthInsurance%                     69602 non-null  float64
 7   arthritis%                             69602 non-null  float64
 8   bingeDrinking%                         69602 non-null  float64
 9   highBP%                                69602 non-null  float64
 10  medicineToLowerBP%                     69602 non-null  float64
 11  nonSkinCancer%                         69602 non-null  float64
 12  currentAsthma%                         69602 non-null  float64
 13  cervicalCancer%                        71580 non-null  float64
 14  coronaryHeartDisease%                  69602 non-null  float64
 15  routineCheckUp%                        69602 non-null  float64
 16  cholestorolScreening%                  69602 non-null  float64
 17  colonScreening%                        71580 non-null  float64
 18  chronicObstructivePulmonaryDisease%    69602 non-null  float64
 19  menUpToDateOnVaccinesAndScreenings%    71543 non-null  float64
 20  womenUpToDateOnVaccinesAndScreenings%  71556 non-null  float64
 21  currentSmoking%                        69602 non-null  float64
 22  routineDentalCheckup%                  71580 non-null  float64
 23  depression%                            69602 non-null  float64
 24  diabetes%                              69602 non-null  float64
 25  fairOrGoodHealth%                      69602 non-null  float64
 26  highCholestorol%                       69602 non-null  float64
 27  chronicKidneyDisease%                  69602 non-null  float64
 28  noLeisurelyPhysicalActivity%           69602 non-null  float64
 29  mammographyUseWomen%                   71579 non-null  float64
 30  badMentalHealth%                       69602 non-null  float64
 31  obesity%                               69602 non-null  float64
 32  badPhysicalHealth%                     69602 non-null  float64
 33  lessThan7HoursOfSleep%                 71580 non-null  float64
 34  stroke%                                69602 non-null  float64
 35  allTeethLost%                          71566 non-null  float64
 36  state                                  71580 non-null  object
 37  county                                 71580 non-null  object
 38  totalPop                               71580 non-null  int64
 39  men                                    71580 non-null  int64
 40  women                                  71580 non-null  int64
 41  hispanic                               71580 non-null  float64
 42  white                                  71580 non-null  float64
 43  black                                  71580 non-null  float64
 44  native                                 71580 non-null  float64
 45  asian                                  71580 non-null  float64
 46  pacific                                71580 non-null  float64
 47  votingAgeCitizen                       71580 non-null  int64
 48  income                                 71580 non-null  float64
 49  incomeErr                              71580 non-null  float64
 50  incomePerCap                           71580 non-null  float64
 51  incomePerCapErr                        71580 non-null  float64
 52  poverty                                71580 non-null  float64
 53  childPoverty                           71580 non-null  float64
 54  professional                           71580 non-null  float64
 55  service                                71580 non-null  float64
 56  office                                 71580 non-null  float64
 57  construction                           71580 non-null  float64
 58  production                             71580 non-null  float64
 59  drive                                  71580 non-null  float64
 60  carpool                                71580 non-null  float64
 61  transit                                71580 non-null  float64
 62  walk                                   71580 non-null  float64
 63  otherTransp                            71580 non-null  float64
 64  workAtHome                             71580 non-null  float64
 65  meanCommute                            71580 non-null  float64
 66  employed                               71580 non-null  int64
 67  privateWork                            71580 non-null  float64
 68  publicWork                             71580 non-null  float64
 69  selfEmployed                           71580 non-null  float64
 70  familyWork                             71580 non-null  float64
 71  unemployment                           71580 non-null  float64
 72  %LessThan9thGrade                      71580 non-null  float64
 73  %HighSchoolGraduate                    71580 non-null  float64
 74  %SomeCollege,NoDegree                  71580 non-null  float64
 75  %AssociatesDegree                      71580 non-null  float64
 76  %BachelorsDegree                       71580 non-null  float64
 77  %GraduateOrProfessionalDegree          71580 non-null  float64
 78  %PercentHighSchoolGraduateOrHigher     71580 non-null  float64
 79  %PercentBachelorsDegreeOrHigher        71580 non-null  float64
 80  %PovertyLessThanHighSchoolGraduate     71580 non-null  float64
 81  %PovertyHighSchoolGraduate             71580 non-null  float64
 82  %PovertySomeCollegeOrAssociatesDegree  71580 non-null  float64
 83  %PovertyBachelorsDegreeOrHigher        71580 non-null  float64
dtypes: float64(71), int64(8), object(5)
memory usage: 46.4+ MB

Remove the null values because there don't seem to be that many

In [7]:
finalDF = finalDF.dropna()

In [8]:
finalDF.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 69557 entries, 0 to 71579
Data columns (total 84 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   stateInitials                          69557 non-null  object
 1   stateName                              69557 non-null  object
 2   countyName                             69557 non-null  object
 3   countyID                               69557 non-null  int64
 4   tractID                                69557 non-null  int64
 5   population                             69557 non-null  int64
 6   noHealthInsurance%                     69557 non-null  float64
 7   arthritis%                             69557 non-null  float64
 8   bingeDrinking%                         69557 non-null  float64
 9   highBP%                                69557 non-null  float64
 10  medicineToLowerBP%                     69557 non-null  float64
 11  nonSkinCancer%                         69557 non-null  float64
 12  currentAsthma%                         69557 non-null  float64
 13  cervicalCancer%                        69557 non-null  float64
 14  coronaryHeartDisease%                  69557 non-null  float64
 15  routineCheckUp%                        69557 non-null  float64
 16  cholestorolScreening%                  69557 non-null  float64
 17  colonScreening%                        69557 non-null  float64
 18  chronicObstructivePulmonaryDisease%    69557 non-null  float64
 19  menUpToDateOnVaccinesAndScreenings%    69557 non-null  float64
 20  womenUpToDateOnVaccinesAndScreenings%  69557 non-null  float64
 21  currentSmoking%                        69557 non-null  float64
 22  routineDentalCheckup%                  69557 non-null  float64
 23  depression%                            69557 non-null  float64
 24  diabetes%                              69557 non-null  float64
 25  fairOrGoodHealth%                      69557 non-null  float64
 26  highCholestorol%                       69557 non-null  float64
 27  chronicKidneyDisease%                  69557 non-null  float64
 28  noLeisurelyPhysicalActivity%           69557 non-null  float64
 29  mammographyUseWomen%                   69557 non-null  float64
 30  badMentalHealth%                       69557 non-null  float64
 31  obesity%                               69557 non-null  float64
 32  badPhysicalHealth%                     69557 non-null  float64
 33  lessThan7HoursOfSleep%                 69557 non-null  float64
 34  stroke%                                69557 non-null  float64
 35  allTeethLost%                          69557 non-null  float64
 36  state                                  69557 non-null  object
 37  county                                 69557 non-null  object
 38  totalPop                               69557 non-null  int64
 39  men                                    69557 non-null  int64
 40  women                                  69557 non-null  int64
 41  hispanic                               69557 non-null  float64
 42  white                                  69557 non-null  float64
 43  black                                  69557 non-null  float64
 44  native                                 69557 non-null  float64
 45  asian                                  69557 non-null  float64
 46  pacific                                69557 non-null  float64
 47  votingAgeCitizen                       69557 non-null  int64
 48  income                                 69557 non-null  float64
 49  incomeErr                              69557 non-null  float64
 50  incomePerCap                           69557 non-null  float64
 51  incomePerCapErr                        69557 non-null  float64
 52  poverty                                69557 non-null  float64
 53  childPoverty                           69557 non-null  float64
 54  professional                           69557 non-null  float64
 55  service                                69557 non-null  float64
 56  office                                 69557 non-null  float64
 57  construction                           69557 non-null  float64
 58  production                             69557 non-null  float64
 59  drive                                  69557 non-null  float64
 60  carpool                                69557 non-null  float64
 61  transit                                69557 non-null  float64
 62  walk                                   69557 non-null  float64
 63  otherTransp                            69557 non-null  float64
 64  workAtHome                             69557 non-null  float64
 65  meanCommute                            69557 non-null  float64
 66  employed                               69557 non-null  int64
 67  privateWork                            69557 non-null  float64
 68  publicWork                             69557 non-null  float64
 69  selfEmployed                           69557 non-null  float64
 70  familyWork                             69557 non-null  float64
 71  unemployment                           69557 non-null  float64
 72  %LessThan9thGrade                      69557 non-null  float64
 73  %HighSchoolGraduate                    69557 non-null  float64
 74  %SomeCollege,NoDegree                  69557 non-null  float64
 75  %AssociatesDegree                      69557 non-null  float64
 76  %BachelorsDegree                       69557 non-null  float64
 77  %GraduateOrProfessionalDegree          69557 non-null  float64
 78  %PercentHighSchoolGraduateOrHigher     69557 non-null  float64
 79  %PercentBachelorsDegreeOrHigher        69557 non-null  float64
 80  %PovertyLessThanHighSchoolGraduate     69557 non-null  float64
 81  %PovertyHighSchoolGraduate             69557 non-null  float64
 82  %PovertySomeCollegeOrAssociatesDegree  69557 non-null  float64
 83  %PovertyBachelorsDegreeOrHigher        69557 non-null  float64
dtypes: float64(71), int64(8), object(5)
memory usage: 45.1+ MB

Drop the duplicate columns \(Keep State to verify a successful merge\), and reset the index

In [9]:
finalDF.drop('totalPop',axis=1)
finalDF.drop('county',axis=1)
finalDF.reset_index(drop=True)

,stateInitials,stateName,countyName,countyID,tractID,population,noHealthInsurance%,arthritis%,bingeDrinking%,highBP%,...,"%SomeCollege,NoDegree",%AssociatesDegree,%BachelorsDegree,%GraduateOrProfessionalDegree,%PercentHighSchoolGraduateOrHigher,%PercentBachelorsDegreeOrHigher,%PovertyLessThanHighSchoolGraduate,%PovertyHighSchoolGraduate,%PovertySomeCollegeOrAssociatesDegree,%PovertyBachelorsDegreeOrHigher
0,AZ,Arizona,Maricopa,4013,4013422643,5789,11.9,17.0,19.9,23.7,...,28.8,12.5,23.8,9.8,95.3,33.5,14.8,10.0,5.7,2.0
1,CA,California,Sacramento,6067,6067007402,6180,15.4,24.6,19.6,30.5,...,24.7,7.8,9.9,3.2,82.9,13.1,45.0,23.5,13.3,6.9
2,AL,Alabama,Madison,1089,1089000201,760,25.4,36.0,10.5,53.7,...,27.3,6.0,7.8,2.5,74.3,10.3,45.8,20.4,26.4,22.6
3,AL,Alabama,Montgomery,1101,1101002202,1185,25.2,36.1,10.9,54.6,...,12.0,3.7,3.4,0.9,68.1,4.3,35.5,26.6,19.2,0.0
4,AL,Alabama,Butler,1013,1013952800,1394,14.3,36.0,13.4,43.0,...,17.3,10.3,20.3,13.8,91.2,34.1,19.8,21.7,10.2,10.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69552,WI,Wisconsin,Milwaukee,55079,55079120101,3953,9.0,30.4,22.7,30.3,...,22.7,6.1,26.4,13.8,93.9,40.2,30.3,5.0,7.2,0.0
69553,WI,Wisconsin,Barron,55005,55005000300,4215,12.1,30.8,20.5,33.8,...,20.3,12.9,11.3,3.6,87.5,14.9,22.0,11.1,10.7,8.2
69554,WI,Wisconsin,Ozaukee,55089,55089620100,6079,9.9,25.3,25.1,29.2,...,23.1,13.0,16.9,6.8,92.6,23.6,8.0,7.7,4.8,7.8
69555,WI,Wisconsin,Waushara,55137,55137960800,4515,15.8,31.9,19.5,36.8,...,23.5,6.5,10.0,5.3,84.1,15.3,27.3,16.3,5.7,3.0
69556,WI,Wisconsin,Outagamie,55087,55087010100,2762,14.2,20.2,25.8,25.5,...,25.0,12.9,15.5,6.0,89.5,21.5,57.5,25.1,16.6,6.8

Verify a successful merge by ensuring that the 'state' and 'stateName' columns hold the same values

In [10]:
### If all elements are equal, the sum is eual to the length, so printing 1 means that the merge was successful
print(sum(finalDF['stateName']==finalDF['state'])/len(finalDF['stateName']))

1.0

Save the ready-to-use data as a new file

In [12]:
finalDF.to_csv('../Clean Data/finalDataset.csv', index=False)